# Project-Level Serena Configuration for Aiko
# Swift/SwiftUI AI Assistant Project Configuration

# Server Configuration - Project-Specific Overrides
server:
  autoIndex: true
  indexPath: .serena/index
  
# Project-Specific Settings
project:
  name: "aiko"
  type: "swift_ios_app"
  language: "swift"
  framework: "swiftui"
  
# GUI and Dashboard Settings
gui_log_window: false
web_dashboard: true
web_dashboard_open_on_launch: false
log_level: 20

# Performance Tuning for iOS Development
trace_lsp_communication: false
tool_timeout: 300  # Extended for Swift compilation
max_concurrent_operations: 4

# Tool Configuration - iOS/Swift Optimized
excluded_tools: []
included_optional_tools: [
  "symbol_navigation",
  "swift_refactoring", 
  "swiftui_preview"
]

# Statistics and Analytics
record_tool_usage_stats: true
token_count_estimator: TIKTOKEN_GPT4O

# Swift/SwiftUI Language Server Configuration
languageServers:
  swift:
    command: sourcekit-lsp
    args: []
    fileExtensions: [".swift"]
    rootPatterns: ["Package.swift", "*.xcodeproj", "*.xcworkspace"]
    workspaceConfiguration:
      swift:
        # SwiftUI-specific settings
        swiftui: 
          enabled: true
          preview_support: true
          binding_analysis: true
        # Enhanced completion for iOS development
        completion:
          maxResults: 100
          includeSystemModules: true
          prioritizeSwiftUI: true
        # Advanced diagnostics
        diagnostics:
          enableExperimental: true
          swift_version: "5.9"
          target_platform: "ios"
        # Semantic features
        semanticHighlighting: true
        symbolGraph: true
        # Code formatting
        formatting:
          enable: true
          indentWidth: 4
          tabsOrSpaces: "spaces"

# Memory Configuration for Project Knowledge
memory:
  enabled: true
  persistence_path: ".serena/memories"
  max_context_size: 8192
  auto_save_interval: 300

# iOS Development Specific Settings
ios_development:
  simulator_support: true
  xcode_integration: true
  swift_package_manager: true
  cocoapods_support: false